/**
 * QuestDB restore 模块单元测试
 */

import { describe, it, after } from 'node:test'
import { join } from 'path'
import { writeFile, rm, mkdir } from 'fs/promises'
import { tmpdir } from 'os'
import { assert, assertEqual } from '../utils/assertions'
import {
  detectBackupFormat,
  parseConnectionString,
} from '../../engines/questdb/restore'

describe('QuestDB Restore Module', () => {
  const testDir = join(tmpdir(), 'questdb-test-' + Date.now())

  after(async () => {
    try {
      await rm(testDir, { recursive: true, force: true })
    } catch {
      // 忽略错误（例如，如果已被清理则忽略ENOENT）
    }
  })

  describe('detectBackupFormat', () => {
    it('should detect .sql file by extension', async () => {
      await mkdir(testDir, { recursive: true })
      const sqlPath = join(testDir, 'backup.sql')
      await writeFile(
        sqlPath,
        '-- QuestDB backup\nCREATE TABLE test (id LONG);',
      )

      const format = await detectBackupFormat(sqlPath)
      assertEqual(format.format, 'sql', '应检测为sql')
      assert(
        format.description.includes('SQL'),
        '描述应提及SQL',
      )

      await rm(sqlPath, { force: true })
    })

    it('should detect SQL content by patterns', async () => {
      await mkdir(testDir, { recursive: true })
      const backupPath = join(testDir, 'backup.bak')
      await writeFile(
        backupPath,
        'CREATE TABLE test (id LONG);\nINSERT INTO test VALUES (1);',
      )

      const format = await detectBackupFormat(backupPath)
      assertEqual(format.format, 'sql', '应通过内容检测SQL')

      await rm(backupPath, { force: true })
    })

    it('should detect QuestDB-specific SQL comments', async () => {
      await mkdir(testDir, { recursive: true })
      const backupPath = join(testDir, 'backup.bak')
      await writeFile(
        backupPath,
        '-- QUESTDB backup generated by SpinDB\nSELECT 1;',
      )

      const format = await detectBackupFormat(backupPath)
      assertEqual(format.format, 'sql', '应通过注释检测QuestDB SQL')

      await rm(backupPath, { force: true })
    })

    it('should return unknown for non-SQL files', async () => {
      await mkdir(testDir, { recursive: true })
      const textPath = join(testDir, 'backup.txt')
      await writeFile(textPath, 'This is not a SQL backup')

      const format = await detectBackupFormat(textPath)
      assertEqual(format.format, 'unknown', '应检测为unknown')

      await rm(textPath, { force: true })
    })
  })

  describe('parseConnectionString', () => {
    it('should parse postgresql connection string', () => {
      const result = parseConnectionString(
        'postgresql://admin:quest@127.0.0.1:8812/qdb',
      )
      assertEqual(result.host, '127.0.0.1', 'host应为127.0.0.1')
      assertEqual(result.port, 8812, 'port应为8812')
      assertEqual(result.database, 'qdb', 'database应为qdb')
      assertEqual(result.user, 'admin', 'user应为admin')
      assertEqual(result.password, 'quest', 'password应为quest')
    })

    it('should parse postgres protocol', () => {
      const result = parseConnectionString(
        'postgres://admin:quest@localhost:8812/qdb',
      )
      assertEqual(result.host, 'localhost', 'host应为localhost')
      assertEqual(result.port, 8812, 'port应为8812')
    })

    it('should use QuestDB default port when not specified', () => {
      const result = parseConnectionString('postgresql://admin@127.0.0.1/qdb')
      assertEqual(
        result.port,
        8812,
        '默认port应为8812（QuestDB默认值）',
      )
    })

    it('should parse connection string without password and use default', () => {
      const result = parseConnectionString(
        'postgresql://admin@127.0.0.1:8812/qdb',
      )
      assertEqual(result.user, 'admin', 'user应为admin')
      assertEqual(result.password, 'quest', 'password应默认为quest')
    })

    it('should throw for invalid connection string', () => {
      try {
        parseConnectionString('invalid')
        assert(false, '应抛出异常')
      } catch (error) {
        assert(error instanceof Error, '应抛出Error')
      }
    })

    it('should accept any protocol and parse it', () => {
      // 实现将questdb://规范化为postgresql://并解析任何URL
      const result = parseConnectionString(
        'questdb://admin:quest@127.0.0.1:8812/qdb',
      )
      assertEqual(result.host, '127.0.0.1', 'host应为127.0.0.1')
      assertEqual(result.port, 8812, 'port应为8812')
    })

    it('should throw for empty connection string', () => {
      try {
        parseConnectionString('')
        assert(false, '应抛出异常')
      } catch (error) {
        assert(error instanceof Error, '应抛出Error')
      }
    })
  })
})
